"""add currency column

Revision ID: 5a41f9c50063
Revises: fc914c1bd24a
Create Date: 2026-08-06 23:25:40.042760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a41f9c50063'
down_revision = 'fc914c1bd24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'currency',
                sa.String(length=10),
                nullable=False,
                server_default='USD'
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
