"""add plan_data

Revision ID: fc914c1bd24a
Revises: fd3fef13759f
Create Date: 2026-08-06 21:23:24.257221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc914c1bd24a'
down_revision = 'fd3fef13759f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('plan_data')

    # ### end Alembic commands ###
